# Generated by Django 2.2 on 2022-02-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isActivate',
            new_name='is_activate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
